### PR TITLE
Replace vector suppressor with universal error catcher

### PR DESCRIPTION
**Pull request by gdavid04**

### CODE REVIEW

**Comment by yrsegal** [comment]
Who asked for this

**Comment by gdavid04** [comment]
It is more useful than just replacing errors with zero vectors. The vector suppressor can be emulated with just one extra piece and most of the time you would want something other than a zero vector as replacement.

/u/Math321 on Taurus Silver discord:
> Can't do "the position of an entity that doesn't exist" and replace that with 0,0,0.

With this you could replace a nonexistent entity for example.

**Comment by yrsegal** [comment]
Ah, that's all you had to say. Math asked for it. Understandable.

**Comment by Alwinfy** [comment]
damn are we doing call-outs in the issue tracker now

**Comment by yrsegal** [comment]
No I just trust Math's judgement.

**Comment by gdavid04** [comment]
Actually I just had this idea of a much more versatile error suppressor and just found out that others would find it useful too

**Comment by yrsegal** [comment]
Whether or not it was your idea, if Math is for it, I'm ok with it.

**Comment by Kamefrede** [comment]
lgtm

**Pull request merged**
