### PR TITLE
added teleport spell

### PR DESCRIPTION
**Pull request by fingin**

### CODE REVIEW

**Comment by yrsegal** [comment]
uh... what?

**Comment by yrsegal** [comment]
two critiques:

1. teleportation is not supposed to be possible in Psi. That's why Trick: Blink doesn't take a vector.  
2. rebase your commits down to one, if you'd want it to be accepted at all.

**Comment by yrsegal** [comment]
Oh, and your grammar is horrifying.

**Comment by Vazkii** [comment]
top lel

**Comment by JRoffel** [comment]
I like how someone just made a random feature for a mod that he/she didn't even know if we wanted, spend a load of time on it without even being sure that it'll be used... Hoping that their pull request will be merged, and then it gets closed, their work is gone, and no one except him will ever see it again...

Or am I making no sense at all right now?

**Comment by Vazkii** [comment]
This couldn't have taken more than 20 minutes.

**Comment by JRoffel** [comment]
Still 20 minutes that could be spent on gaming :)

**Pull request closed without merging**
