### PR TITLE
Fix break tool and level

### PR DESCRIPTION
**Pull request by BlueAgent**
## Summary
Addresses some of the problems described in #537 
Namely, the CAD being able to harvest blocks that ordinarily require special tools (like Forestry Hives)
Also when a spell is cast, the CAD stack is part of the context, also is saved in projectile and spell circle so it is more likely to be available for the break block spell.
I'm not really happy with the current PR / implementation though so looking for comments and discussion about how it could be changed.

## PR Changes
- Have the CAD stack used to cast a spell available in the spell context
- Makes sure that the CAD acts only as a pickxe, axe and shovel
- Makes sure that the CAD or psimetal tool that casted the spell is used to check harvestability (not the main hand). Before this change it only checked harvest level.
- Makes sure that we use `return new ForgeEventFactory:doPlayerHarvestCheck` mirroring `ForgeHooks::canHarvestBlock` letting the event system decide the fate if the harvest
- Note: Harvest tool classes and harvest levels for vanilla blocks are set properly by forge (See: `ForgeHooks::initTools()`) so harvest levels >= 3 properly harvest obsidian.

## Testing Environment

AutoRegLib-1.3-32
forestry_1.12.2-5.8.2.387
jei_1.12.2-4.15.0.291
Psi-r1.1-77

## Demo Videos and Summary

[Before](https://www.youtube.com/watch?v=EDz9URi3ffk)
- All tools and CAD harvest Planks, Dirt, Stone, Coal, Iron, Diamond and **Forestry Hive**
- Psimetal pickaxe also harvests obsidian
- No tools harvest bedrock

[After](https://www.youtube.com/watch?v=-Bf9ZmWXWrA)
- All tools harvest Planks and Dirt
- Psimetal pickaxe also harvests Stone, Coal, Iron, Diamond
- No tools harvest bedrock or Forestry Hives

## Other thoughts

Adding the CAD into spell context and saving it in projectile spells and spell circles is quite an intrustive change. A much simpler solution might be to just have break block fail if it can't find a CAD or tool to use? I think I may just change this PR to be that instead tbh. It would touch way less code that way.

### CODE REVIEW

**Comment by BlueAgent** [comment]
Was kinda hoping for comments on this. Maybe It'll be okay to mark it for review?

**Comment by BlueAgent** [comment]
Could make a PR for 1.14 instead?

I think having a copy of the CAD stack in the context fixes problems with it missing but not well versed in the code base to know the side effects. How are the PR's changes in that respect?

Could also have the spells error out if it can't find CAD or Psi Tool as a less intrusive change.

**Comment by Kamefrede** [comment]
Seems good to me! Will merge to the 1.12 branch, if you want you can do another PR for 1.14, if not I'll upstream the changes.

**Comment by BlueAgent** [comment]
Sorry for getting back to this a so late. Feel free to merge the changes upstream. ❤️

**Pull request merged**
