### PR TITLE
Add subtitles

### LINKED ISSUE #164: [Minor feature] Subtitles
@williewillus has gotten them to work, if examples are needed.

### PR DESCRIPTION
**Pull request by yrsegal**
Closes #164 even though it’s already closed

### CODE REVIEW

**Comment by williewillus** [comment]
maybe make them more...onomatopoeic? Like the vanilla ones have "sheep baahs" "cow moos" or "item plops"

**Comment by yrsegal** [comment]
"block breaks"
"footsteps"

**Comment by williewillus** [comment]
?shrug these just seem a bit bland

**Comment by yrsegal** [comment]
well, V can change them if she wishes ¯\_(ツ)_/¯

**Pull request merged**
